### ISSUE TITLE
Crate /cr buy bugs.

### ISSUE THREAD

**Issue by SynxPlays** [iAmWillX/CrateReloaded#22]
Hello,
I have found two bugs with /cr buy command. 
First, that you write /cr buy FoodKey 1 , it doesn't give key but Error crate.
Second, that you write /cr buy FoodKey 1, it gives you 1 key crate for 500$, but when you type /cr buy FoodKey 5, it gives you 5 key crates and again for 500$...

**Comment by iAmWillX** [comment]
Refer to #20

**Comment by iAmWillX** [comment]
The second issue will be fixed tomorrow. Thank you for the report.
